# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandupTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('jira_issue_id', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('initial_estimate_in_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('is_template', models.BooleanField(default=False)),
                ('created_by_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'standup_task',
            },
        ),
        migrations.CreateModel(
            name='StandupTaskWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent_in_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expected_outcome', models.CharField(blank=True, max_length=64, null=True)),
                ('actual_outcome', models.CharField(blank=True, max_length=64, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('standup_task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='standup.StandupTask')),
            ],
            options={
                'db_table': 'standup_task_work',
            },
        ),
    ]
