# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 03:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0002_auto_20160314_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='jira_project_id',
        ),
        migrations.RemoveField(
            model_name='standuptask',
            name='jira_issue_id',
        ),
        migrations.AddField(
            model_name='project',
            name='jira_project_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='standuptask',
            name='jira_issue_key',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
