# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 03:07
from __future__ import unicode_literals

from django.db import migrations

def insert_initial_data(apps, schema_editor):
    Project = apps.get_model('standup', 'Project')
    proj = Project(name="Test Project", jira_project_key="DER")
    proj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0003_auto_20160314_2131'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
