# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-05 23:08
from __future__ import unicode_literals

from django.db import migrations

from authentication.models import ApplicationUser


def insert_data(apps, schema_editor):
    Org = apps.get_model('authentication', 'Organization')
    org = Org(name="Test Org")
    org.save()

    ApplicationUser.objects.create_user("e@j.com", "e", "j", 1, True, "Password123")


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_data)
    ]
