# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
